# -*- coding: utf-8 -*-
"""Numpy Basics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZkuNOBXhYsBOYih_sPoEMWGb-kiGVjN
"""

pip install numpy

a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

import numpy as np
a = np.array([1,2,3,4,5,6])
a

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a[1])

import numpy as np
a = np.array([1, 2, 3])
a

a2=np.zeros(2)
a2

a = np.ones(2)
a

b=np.empty(2)
b

c= np.arange(5)
c

d= np.arange(2,9,2)
d

e=np.arange(3,16,2)
e

e= np.arange(3,16,3)
e

f= np.linspace(0, 10, num=5)
f

x = np.ones(2, dtype=np.int64)
x